# Generated by Django 4.0.1 on 2022-02-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementIdMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_id', models.PositiveIntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MigratedMissingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_created_date', models.DateTimeField(auto_now_add=True)),
                ('table', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('value', models.JSONField()),
            ],
        ),
    ]
